services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  db_init:
    image: mysql:latest
    depends_on:
      - db
    volumes:
      - ./scripts:/scripts
    entrypoint: ["sh", "-c", "while ! mysqladmin ping -h db --silent; do sleep 1; done && mysql -h db -u${MYSQL_USER} -p${MYSQL_PASSWORD} < /scripts/init.sql"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db
